(() => {
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),mini=$('#minimap'),mctx=mini.getContext('2d'),TAU=Math.PI*2;
const SPECIES=[
{id:'algae',name:'Algae',role:'food',color:'#88e58a',r:8,energy:10,desc:'Photosynthetic nutrient producers. Easy calories for young microbes.'},
{id:'bacteria',name:'Bacteria',role:'food',color:'#b8e26a',r:6,energy:8,desc:'Common microbial prey. Some colonies carry extra energy.'},
{id:'paramecium',name:'Paramecium',role:'neutral',color:'#8adad6',r:13,energy:18,desc:'Fast-moving ciliate. Can be prey or competitor depending on mass.'},
{id:'beneficial',name:'Beneficial Microbe',role:'heal',color:'#69f4d2',r:8,energy:22,desc:'A symbiotic microbe that restores energy and a little health.'},
{id:'predator',name:'Predatory Microbe',role:'predator',color:'#e7a8ff',r:18,energy:0,desc:'Aggressive hunters that pursue smaller cells.'},
{id:'virus',name:'Virus',role:'virus',color:'#ff7275',r:10,energy:0,desc:'Contact damages health and briefly scrambles movement.'},
{id:'toxic',name:'Toxic Microbe',role:'toxic',color:'#e9cc62',r:15,energy:0,desc:'Releases harmful compounds and drains energy nearby.'}];
const state={mode:'survival',running:false,paused:false,sound:true,time:0,score:0,eaten:0,xp:0,evo:1,mass:12,health:100,energy:82,world:{w:2600,h:1800},cam:{x:1300,y:900},input:{x:0,y:0,mouse:null},organisms:[],particles:[],hazards:[],last:0,player:{x:1300,y:900,vx:0,vy:0,r:24,mass:12,ability:0}};
const organisms=state.organisms;function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);mini.width=280;mini.height=160}addEventListener('resize',resize);resize();
const rng=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=a=>a[(Math.random()*a.length)|0],fmt=t=>String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');
function spawn(kind,x,y){const s=SPECIES.find(v=>v.id===kind),o={id:(crypto.randomUUID?crypto.randomUUID():String(Math.random())),kind,x:x??rng(50,state.world.w-50),y:y??rng(80,state.world.h-50),vx:rng(-.5,.5),vy:rng(-.5,.5),r:s.r*rng(.78,1.25),energy:s.energy,age:rng(0,10),hue:rng(0,TAU)};organisms.push(o);return o}
function seedWorld(){organisms.length=0;const counts={algae:65,bacteria:90,paramecium:25,beneficial:12,predator:9,virus:16,toxic:6};Object.entries(counts).forEach(([k,n])=>{for(let i=0;i<n;i++)spawn(k)});state.hazards=[{x:500,y:330,r:180,type:'toxic',strength:.7},{x:2060,y:1360,r:210,type:'cold',strength:.4},{x:1550,y:420,r:155,type:'antibiotic',strength:.45}]}
function hideAll(){['menuScreen','encyclopediaScreen','gameScreen'].forEach(id=>$('#'+id).classList.add('hidden'))}function menu(){state.running=false;hideAll();$('#menuScreen').classList.remove('hidden')}
function reset(mode){state.mode=mode;state.running=true;state.paused=false;state.time=0;state.score=0;state.eaten=0;state.xp=0;state.evo=1;state.mass=12;state.health=100;state.energy=82;state.player={x:1300,y:900,vx:0,vy:0,r:24,mass:12,ability:0};seedWorld();hideAll();$('#gameScreen').classList.remove('hidden');$('#modeLabel').textContent=mode==='evolution'?'EVOLUTION RUN':mode.toUpperCase();$('#gameOverOverlay').classList.add('hidden');$('#pauseOverlay').classList.add('hidden');$('#speciesName').textContent='Protozoa';$('#abilityName').textContent='Ciliate Drift';updateHUD()}
function renderEncyclopedia(){$('#encyclopediaGrid').innerHTML=SPECIES.map((s,i)=>'<article class="micro-card"><div class="micro-illustration"><div class="blob" style="transform:scale('+(0.7+i*.05)+');filter:hue-rotate('+(i*27)+'deg)"></div></div><div class="eyebrow">'+s.role+'</div><h3>'+s.name+'</h3><p>'+s.desc+'</p></article>').join('')}
function openEncyclopedia(){hideAll();$('#encyclopediaScreen').classList.remove('hidden');renderEncyclopedia()}
function worldToScreen(x,y){return{x:x-state.cam.x+innerWidth/2,y:y-state.cam.y+innerHeight/2}}
function addParticle(x,y,color,count){for(let i=0;i<(count||6);i++)state.particles.push({x:x,y:y,vx:rng(-1.5,1.5),vy:rng(-1.5,1.5),life:rng(.35,.9),max:1,color:color,r:rng(1,3)})}
function effectBurst(x,y,color){addParticle(x,y,color,24)}
function consume(o){const s=SPECIES.find(v=>v.id===o.kind);state.eaten++;state.score+=Math.round(o.r*o.r);state.mass+=Math.max(.5,o.r*.1);state.player.mass=state.mass;state.energy=clamp(state.energy+s.energy*.72,0,100);state.xp+=Math.round(s.energy*1.2);effectBurst(o.x,o.y,s.color);const idx=organisms.indexOf(o);if(idx>=0)organisms.splice(idx,1);if(s.role==='heal')state.health=clamp(state.health+8,0,100)}
function damage(amount){state.health-=amount;addParticle(state.player.x,state.player.y,'#ff6e71',4);if(state.health<=0)endGame('Your microbe was consumed.')}
function evolve(){const cost=state.evo*30;if(state.xp<cost||state.energy<55)return;state.xp-=cost;state.energy-=18;state.evo++;state.player.r*=1.18;state.mass*=1.18;state.player.mass=state.mass;state.health=clamp(state.health+18,0,100);effectBurst(state.player.x,state.player.y,'#b7f16a');state.player.ability=state.evo%3;const names=['Protozoa','Cyanocell','Macroflagellate','Preda-Cyst','Apex Microbe'],abilities=['Ciliate Drift','Photosynthetic Surge','Flagellar Dash','Predator Pulse','Apex Split'];$('#speciesName').textContent=names[Math.min(state.evo-1,4)];$('#abilityName').textContent=abilities[Math.min(state.evo-1,4)]}
function ability(){if(!state.running||state.paused||state.energy<14)return;state.energy-=14;const p=state.player,ang=Math.atan2(state.input.y,state.input.x)||0;p.vx+=Math.cos(ang)*2.9;p.vy+=Math.sin(ang)*2.9;effectBurst(p.x,p.y,'#66f2d1');organisms.filter(o=>dist(p,o)<p.r*2&&o.kind==='virus').forEach(o=>{o.x+=Math.cos(ang)*70;o.y+=Math.sin(ang)*70})}
function togglePause(){state.paused=!state.paused;$('#pauseOverlay').classList.toggle('hidden',!state.paused)}
function endGame(title){state.running=false;$('#finalMass').textContent=Math.round(state.mass);$('#finalEaten').textContent=state.eaten;$('#finalTime').textContent=fmt(state.time);$('#gameOverTitle').textContent=title;$('#gameOverOverlay').classList.remove('hidden')}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='p'||k==='escape'){if(state.running)togglePause()}if(k==='e')evolve();if(k===' ')ability();if(k==='w'||k==='arrowup')state.input.y=-1;if(k==='s'||k==='arrowdown')state.input.y=1;if(k==='a'||k==='arrowleft')state.input.x=-1;if(k==='d'||k==='arrowright')state.input.x=1});
addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(['w','s','arrowup','arrowdown'].includes(k))state.input.y=0;if(['a','d','arrowleft','arrowright'].includes(k))state.input.x=0});canvas.addEventListener('pointermove',e=>{state.input.mouse={x:e.clientX,y:e.clientY}});canvas.addEventListener('pointerdown',()=>{if(innerWidth>650)ability()});$('#abilityBtn').addEventListener('click',ability);
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(a==='play')reset('survival');if(a==='evolution')reset('evolution');if(a==='sandbox')reset('sandbox');if(a==='encyclopedia')openEncyclopedia();if(a==='menu')menu();if(a==='pause')togglePause();if(a==='restart')reset(state.mode);if(a==='sound'){state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'SOUND ON':'SOUND OFF'}});
function update(dt){state.time+=dt;const p=state.player;let ix=state.input.x,iy=state.input.y;if(state.input.mouse){const dx=state.input.mouse.x-innerWidth/2,dy=state.input.mouse.y-innerHeight/2,mag=Math.hypot(dx,dy);if(mag>30){ix=dx/mag;iy=dy/mag}}p.vx+=ix*.11;p.vy+=iy*.11;p.vx*=Math.pow(.90,dt*60);p.vy*=Math.pow(.90,dt*60);const speed=state.mode==='sandbox'?4.2:3.4+Math.min(1.4,state.evo*.12);p.x=clamp(p.x+p.vx*speed*dt*60,p.r,state.world.w-p.r);p.y=clamp(p.y+p.vy*speed*dt*60,p.r,state.world.h-p.r);state.energy=clamp(state.energy-dt*(state.mode==='sandbox'?.7:1.05),0,100);if(state.energy<=0)damage(dt*2.4);
for(const o of organisms){o.age+=dt;const d=dist(p,o),dx=p.x-o.x,dy=p.y-o.y,mag=Math.max(1,d);if(o.kind==='predator'){o.vx+=(dx/mag)*.025;o.vy+=(dy/mag)*.025;if(d<p.r+o.r&&o.r>p.r*.72)damage(dt*20)}else if(o.kind==='virus'){o.vx*=.98;o.vy*=.98;if(d<p.r+o.r)damage(dt*7);if(d<180){o.vx+=(dx/mag)*-.008;o.vy+=(dy/mag)*-.008}}else if(o.kind==='toxic'){o.vx+=Math.cos(o.age*2.1)*.006;o.vy+=Math.sin(o.age*1.7)*.006;if(d<p.r+o.r)damage(dt*10);if(d<o.r*4)state.energy=clamp(state.energy-dt*2,0,100)}else{o.vx*=.985;o.vy*=.985;if(o.kind==='paramecium'){o.vx+=Math.cos(o.age*2.3+o.hue)*.012;o.vy+=Math.sin(o.age*1.9+o.hue)*.012}else{o.vx+=Math.sin(o.age+o.hue)*.003;o.vy+=Math.cos(o.age*1.3+o.hue)*.003}}const os=Math.hypot(o.vx,o.vy);if(os>1.2){o.vx/=os/1.2;o.vy/=os/1.2}o.x=clamp(o.x+o.vx*dt*45,o.r,state.world.w-o.r);o.y=clamp(o.y+o.vy*dt*45,o.r,state.world.h-o.r)}
for(let i=organisms.length-1;i>=0;i--){const o=organisms[i];if(dist(p,o)<p.r+o.r){if(['algae','bacteria','paramecium','beneficial'].includes(o.kind)&&p.r>=o.r*1.12)consume(o);else if(o.kind==='predator'&&o.r>p.r*1.05)damage(dt*38)}}for(const h of state.hazards){if(Math.hypot(p.x-h.x,p.y-h.y)<h.r){if(h.type==='antibiotic')damage(dt*(2+h.strength*4));else if(h.type==='cold'){p.vx*=.992;p.vy*=.992;state.energy=clamp(state.energy-dt*h.strength,0,100)}else damage(dt*h.strength*2)}}if(Math.random()<dt*.8)spawn(rnd(['algae','bacteria','paramecium','virus']));if(Math.random()<dt*.13&&organisms.length>260)organisms.splice((Math.random()*organisms.length)|0,1);state.cam.x+=(p.x-state.cam.x)*.08;state.cam.y+=(p.y-state.cam.y)*.08;state.particles.forEach(q=>{q.x+=q.vx*dt*60;q.y+=q.vy*dt*60;q.life-=dt});state.particles=state.particles.filter(q=>q.life>0);updateHUD()}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#06171b';ctx.fillRect(0,0,w,h);const bg=ctx.createRadialGradient(w*.48,h*.48,20,w*.48,h*.48,Math.max(w,h)*.72);bg.addColorStop(0,'#0a2529');bg.addColorStop(1,'#031013');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const step=95;for(let x=Math.floor((state.cam.x-w/2)/step)*step;x<state.cam.x+w/2+step;x+=step){for(let y=Math.floor((state.cam.y-h/2)/step)*step;y<state.cam.y+h/2+step;y+=step){const s=worldToScreen(x,y);ctx.fillStyle='rgba(97,221,194,'+(.05+.02*Math.sin(x*.01+y*.013))+')';ctx.fillRect(s.x,s.y,1,1)}}for(const z of state.hazards){const s=worldToScreen(z.x,z.y),grd=ctx.createRadialGradient(s.x,s.y,10,s.x,s.y,z.r);grd.addColorStop(0,'rgba(255,118,118,.11)');grd.addColorStop(1,'rgba(255,118,118,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(s.x,s.y,z.r,0,TAU);ctx.fill();ctx.setLineDash([4,8]);ctx.strokeStyle='rgba(240,132,130,.17)';ctx.beginPath();ctx.arc(s.x,s.y,z.r*.72,0,TAU);ctx.stroke();ctx.setLineDash([])}for(const o of organisms){const s=worldToScreen(o.x,o.y),spec=SPECIES.find(v=>v.id===o.kind);if(s.x<-60||s.y<-60||s.x>w+60||s.y>h+60)continue;drawOrganism(s.x,s.y,o.r,spec,o.age,o.hue)}for(const q of state.particles){const s=worldToScreen(q.x,q.y);ctx.globalAlpha=Math.max(0,q.life/q.max);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(s.x,s.y,q.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;const ps=worldToScreen(state.player.x,state.player.y);drawPlayer(ps.x,ps.y,state.player.r,state.time);drawMinimap()}
function drawOrganism(x,y,r,spec,age,hue){ctx.save();ctx.translate(x,y);ctx.rotate(hue+age*.2);ctx.shadowBlur=r*1.9;ctx.shadowColor=spec.color;ctx.globalAlpha=.15;ctx.fillStyle=spec.color;ctx.beginPath();ctx.arc(0,0,r*1.6,0,TAU);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=spec.color;ctx.beginPath();if(spec.id==='virus'){for(let i=0;i<10;i++){const a=i*Math.PI/5;ctx.lineTo(Math.cos(a)*r*1.35,Math.sin(a)*r*1.35);ctx.lineTo(Math.cos(a+.14)*r*.8,Math.sin(a+.14)*r*.8)}ctx.closePath()}else{ctx.ellipse(0,0,r*(1+.08*Math.sin(age*2)),r*(.82+.08*Math.cos(age*1.6)),0,0,TAU)}ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(7,28,31,.55)';ctx.beginPath();ctx.arc(-r*.18,-r*.08,r*.14,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(r*.2,r*.17,r*.08,0,TAU);ctx.fill();ctx.restore()}
function drawPlayer(x,y,r,age){ctx.save();ctx.translate(x,y);ctx.rotate(age*.4);for(let i=0;i<10;i++){const a=i*TAU/10;ctx.strokeStyle='rgba(102,242,209,'+(.18+.05*Math.sin(age+i))+')';ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.9,Math.sin(a)*r*.9);ctx.lineTo(Math.cos(a)*r*1.35,Math.sin(a)*r*1.35);ctx.stroke()}ctx.shadowBlur=28;ctx.shadowColor='#66f2d1';ctx.fillStyle='#65e7c5';ctx.beginPath();ctx.ellipse(0,0,r,r*.88,0,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#155650';ctx.beginPath();ctx.arc(-r*.18,-r*.06,r*.23,0,TAU);ctx.fill();ctx.fillStyle='#d9fff4';ctx.beginPath();ctx.arc(r*.22,-r*.16,r*.07,0,TAU);ctx.fill();ctx.restore()}
function drawMinimap(){const w=280,h=160;mctx.clearRect(0,0,w,h);mctx.fillStyle='#06181d';mctx.fillRect(0,0,w,h);const sx=w/state.world.w,sy=h/state.world.h;for(const o of organisms){const spec=SPECIES.find(v=>v.id===o.kind);mctx.fillStyle=spec.color;mctx.globalAlpha=.62;mctx.fillRect(o.x*sx,o.y*sy,2,2)}mctx.globalAlpha=1;mctx.fillStyle='#fff';mctx.beginPath();mctx.arc(state.player.x*sx,state.player.y*sy,3,0,TAU);mctx.fill()}
function updateHUD(){$('#massStat').textContent=Math.round(state.mass);$('#evoStat').textContent=String(state.evo).padStart(2,'0');$('#timeStat').textContent=fmt(state.time);$('#healthText').textContent=Math.round(state.health)+'%';$('#energyText').textContent=Math.round(state.energy)+'%';$('#evolutionText').textContent=Math.min(state.xp,state.evo*30)+' / '+(state.evo*30)+' XP';$('#healthBar').style.width=clamp(state.health,0,100)+'%';$('#energyBar').style.width=clamp(state.energy,0,100)+'%';$('#evoBar').style.width=clamp(state.xp/(state.evo*30)*100,0,100)+'%';$('#objectiveText').textContent=state.mode==='sandbox'?'Explore the ecosystem.':state.eaten<5?'Feed, grow, survive.':'Next mutation is close.';const left=Math.max(0,5-state.eaten);$('#objectiveSub').textContent=state.mode==='sandbox'?'Population and hazards are relaxed.':'Consume '+left+' more organism'+(left===1?'':'s')+' or gather XP';const ranks=[['Amoeba Prime',Math.max(320,Math.round(state.mass*12))],['Cytoblast',Math.max(220,Math.round(state.mass*8.2))],['You',Math.round(state.mass*10)],['Ribocyst',Math.max(140,Math.round(state.mass*5.4))]];$('#leaderboard').innerHTML=ranks.sort((a,b)=>b[1]-a[1]).slice(0,4).map((r,i)=>'<div class="leader-row"><span>'+(i+1)+'. '+r[0]+'</span><b>'+r[1]+'</b></div>').join('')}
function tick(t){const dt=Math.min(.034,(t-state.last)/1000||.016);state.last=t;if(state.running&&!state.paused){update(dt);draw()}else if(!state.running)draw();requestAnimationFrame(tick)}seedWorld();menu();requestAnimationFrame(tick);
})();